version: "3"
services:
  sample-app-web:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - /Development/Sample/sample-app-server/html/sample-app:/sample-app
    ports:
      - "3001:3000"
    # environment:
    #   TZ: 'Asia/Tokyo'
    #   # SECRET_KEY_BASE: 'hogehoge'
    #   RAILS_ENV: 'development'
    #   RAILS_DATABASE: 'app_db'
    #   RAILS_DATABASE_TEST: 'app_db_test'
    #   RAILS_DATABASE_USER: 'root'
    #   RAILS_DATABASE_PASSWORD: 'password'
    #   RAILS_DATABASE_HOST: sample-app-db
    depends_on:
     - sample-app-db
  sample-app-db:
    image: mysql
    # ports:
    #   - 3306:3306
    hostname: sample-app-db
    restart: always
    environment:
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
      - /Development/Sample/sample-app-server/mysql/init:/docker-entrypoint-initdb.d
  sample-app-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=sample-app-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - sample-app-db
    ports:
      - 8080:80
    volumes:
      - /sessions
volumes:
  db-data: